apiVersion: batch/v1
kind: Job
metadata:
  name: team-a-job
  namespace: team-a
  labels:
    kueue.x-k8s.io/queue-name: local-queue
    kueue.x-k8s.io/priority-class: prod-priority
spec:
  template:
    spec:
      containers:
        - name: app
          image: busybox
          command: ["sleep", "3600"]
          resources:
            requests:
              cpu: "7"
              nvidia.com/gpu: 2
            limits:
              nvidia.com/gpu: 2
      restartPolicy: Never
