apiVersion: batch/v1
kind: Job
metadata:
  generateName: curl-job-success-
  namespace: demo
  labels:
    kueue.x-k8s.io/queue-name: user-queue
spec:
  parallelism: 2
  completions: 2
  suspend: true
  template:
    spec:
      containers:
      - name: curl
        image: quay.io/rh_ee_czaccari/curlimages:curl
        command: ["sh", "-c", "sleep 5 && curl http://sample-service"]
        resources:
          requests:
            cpu: 1
            memory: "200Mi"
            nvidia.com/gpu: 1
          limits:
            cpu: 1
            memory: "200Mi"
            nvidia.com/gpu: 1
      restartPolicy: Never
