apiVersion: v1
kind: Pod
metadata:
  name: sample-server
  namespace: demo
  labels:
    app: sample-app
spec:
  containers:
    - name: server
      image: python:3.9-slim
      command: ["python", "-m", "http.server", "80"]
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sample-service
  namespace: demo
spec:
  selector:
    app: sample-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
