#!/usr/bin/env bash

# Copyright 2023 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset
set -o pipefail

for yaml_file_path in $YAML_FILE_PATHS; do
  yaml_contents=$(<"$yaml_file_path")
  readme_file_path=$(dirname "$yaml_file_path")/../README.md

  awk -v yaml_path="$yaml_file_path" -v yaml_contents="$yaml_contents" '
    /<!-- YAML-START: / && $0 ~ yaml_path { in_block = 1; found_yaml = 1; next }
    /<!-- YAML-END -->/ && in_block {
      in_block = 0
      if (!found_generated) {
        print "<!-- Generated by \047make update-readme\047. DO NOT EDIT. -->"
      }
      print "<!-- YAML-START: " yaml_path " -->"
      print "```yaml"
      print yaml_contents
      print "```"
      print "<!-- YAML-END -->"
      next
    }
    /<!-- Generated by \047make update-readme\047. DO NOT EDIT. -->/ && !in_block { found_generated = 1 }
    /<!-- YAML-START: / { found_generated = 0 } # Reset for each YAML block
    !in_block { print }
  ' $readme_file_path > temp.md && mv temp.md $readme_file_path
done