#!/usr/bin/env bash

# Copyright 2025 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset
set -o pipefail

for yaml_file_path_with_index in $YAML_FILE_PATHS_WITH_INDEX; do
  yaml_file_path=$(echo "$yaml_file_path_with_index" | sed -E 's/\[[0-9]+\]$//')
  readme_file_path=$(dirname "$yaml_file_path")/../README.md
  index_in_file=$(echo "$yaml_file_path_with_index" | grep -oE '\[[0-9]+\]' | grep -oE '[0-9]+' || echo "-1")

  awk -v yaml_path="$yaml_file_path" -v index_in_file="$index_in_file" '
    {
      if (index_in_file >= 0) {
        if ($0 ~ ("<!-- YAML-START: " yaml_path "\\[" index_in_file "\\]")) {
          in_block = 1; found_yaml = 1; next
        }
      } else if (index_in_file == -1) {
        if ($0 ~ ("<!-- YAML-START: " yaml_path " -->")) {
          in_block = 1; found_yaml = 1; next
        }
      }
    }
    /<!-- YAML-END -->/ && in_block {
      in_block = 0
      if (!found_generated) {
        print "<!-- Generated by \047make update-readme\047. DO NOT EDIT. -->"
      }
      print "<!-- YAML-START: " yaml_path (index_in_file != -1 ? "[" index_in_file "]" : "") " -->"
      print "```yaml"

      # Read YAML file, handle index logic
      count = 0
      empty_count = 0

      while ((getline line < yaml_path) > 0) {
        if (index_in_file == -1) {
          print line
          continue
        }

        if (line ~ /^---$/) {
          count++
          continue
        }

        if (count < index_in_file) {
          continue
        }

        if (count > index_in_file) {
          break
        }

        if (line ~ /^[[:space:]]*$/) {
          empty_count++
        } else {
          while (empty_count > 0) {
            empty_count--
          }
          print line
        }

      }
      close(yaml_path)

      print "```"
      print "<!-- YAML-END -->"
      next
    }
    /<!-- Generated by \047make update-readme\047. DO NOT EDIT. -->/ && !in_block { found_generated = 1 }
    /<!-- YAML-START: / { found_generated = 0 } # Reset for each YAML block
    !in_block { print }
  ' "$readme_file_path" > temp.md && mv temp.md "$readme_file_path"
done
